spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fleet_db
    username: fleet_user
    password: fleet_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # automatycznie tworzy tabele
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: fleet-service
server:
  port: 8081
